ALTER TYPE "ProposalLayout" ADD VALUE IF NOT EXISTS 'EXECUTIVE';
ALTER TYPE "ProposalLayout" ADD VALUE IF NOT EXISTS 'BLUEPRINT';
ALTER TYPE "ProposalLayout" ADD VALUE IF NOT EXISTS 'SIGNATURE';

ALTER TABLE "Proposal" ADD COLUMN "customerCompanyName" TEXT;
ALTER TABLE "Proposal" ADD COLUMN "customerLogoDataUrl" TEXT;
ALTER TABLE "Proposal" ADD COLUMN "showCustomerLogo" BOOLEAN NOT NULL DEFAULT false;
